---
title: "DC Crash Data"
output: html_notebook
---

# Load Data
```{r, fig.width=4, fig.height=2}
library(tidyverse)
library(lubridate)
crash_data <- read_csv('data/Crashes_in_DC.csv.gz')
crash_data %>% select(FROMDATE, WARD, MAJORINJURIES_BICYCLIST:SPEEDING_INVOLVED ) %>% colnames()
```

# Aggregate
```{r}
crash_data_aggregation <- crash_data %>% select(FROMDATE, WARD, MAJORINJURIES_BICYCLIST:SPEEDING_INVOLVED ) %>% 
  mutate(Date = as.Date(FROMDATE)) %>% 
  # mutate(Involved = case_when(TOTAL_BICYCLES > 0 & TOTAL_PEDESTRIANS > 0 & TOTAL_VEHICLES > 0 ~ 'Bicyclist, Pedestrian, Vehicle',
  #                             TOTAL_BICYCLES > 0 & TOTAL_PEDESTRIANS > 0 ~ 'Bicyclist, Pedestrian',
  #                             TOTAL_BICYCLES > 0 & TOTAL_VEHICLES > 0 ~ 'Bicyclist, Vehicle',
  #                             TOTAL_PEDESTRIANS > 0 & TOTAL_VEHICLES > 0 ~ 'Pedestrian, Vehicle',
  #                             TOTAL_BICYCLES > 0 ~ 'Bicyclist',
  #                             TOTAL_PEDESTRIANS > 0 ~ 'Pedestrian',
  #                             TOTAL_VEHICLES > 0 ~ 'Vehicle',
  #                             TRUE ~ 'Other')) %>% 
  group_by(Month=floor_date(Date, "month")) %>% 
  summarise(Bike = sum(TOTAL_BICYCLES),
            `Cyclist Injuries` = sum(MAJORINJURIES_BICYCLIST + MINORINJURIES_BICYCLIST),
            Pedestrian = sum(TOTAL_PEDESTRIANS),
            `Pedestrian Injuries` = sum(MAJORINJURIES_PEDESTRIAN + MINORINJURIES_PEDESTRIAN),
            Vehicle = sum(TOTAL_VEHICLES),
            `Driver Injuries` = sum(MAJORINJURIES_DRIVER + MINORINJURIES_DRIVER)) %>% 
  filter(Month > '2010-01-01', Month < '2019-01-01') %>% 
  gather(Type, Count, -Month)
```

# Injuries over Time
```{r}
crash_data_aggregation%>% 
  filter(grepl('Injur', Type)) %>% 
  ggplot(aes(x=Month, y = Count)) + 
  geom_point() + 
  geom_smooth() +
  facet_wrap(~ Type, scales = 'free_y') + 
  theme_minimal() +
  xlab('Date')
```

# Counts of Incidents by Bikes, Pedestrians, Vehicles
```{r}
crash_data_aggregation %>% 
  filter(!grepl('Injur', Type)) %>% 
  ggplot(aes(x=Month, y = Count)) + 
  geom_point() + 
  geom_smooth() +
  facet_wrap(~ Type, scales = 'free_y') + 
  theme_minimal() +
  xlab('Date')
```
